#!/bin/sh

# Configure git
git config user.name Babar
git config user.email babar@jungle.org

# Setup a git repository with some content
git init try
cd try
echo a >a
git add a
git commit -m a
cd ..

# Now try to clone it with mercurial-git
exec hg --config extensions.git= clone try try2
