.\"     Title: hgmerge
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.1 <http://docbook.sf.net/>
.\"      Date: 10/19/2007
.\"    Manual: 
.\"    Source: 
.\"
.TH "HGMERGE" "1" "10/19/2007" "" ""
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
hgmerge - default wrapper to merge files in Mercurial SCM system
.SH "SYNOPSIS"
\fIhgmerge\fR local ancestor remote
.sp
.SH "DESCRIPTION"
The hgmerge(1) command provides a graphical interface to merge files in the Mercurial system\. It is a simple wrapper around kdiff3, merge(1) and tkdiff(1), or simply diff(1) and patch(1) depending on what is present on the system\.
.sp
hgmerge(1) is used by the Mercurial SCM if the environment variable HGMERGE is not set\.
.sp
.SH "AUTHOR"
Written by Vincent Danjean <Vincent\.Danjean@free\.fr>
.sp
.SH "SEE ALSO"
hg(1) \- the command line interface to Mercurial SCM
.sp
.SH "COPYING"
Copyright (C) 2005\-2007 Matt Mackall\. Free use of this software is granted under the terms of the GNU General Public License (GPL)\.
.sp
